---
title: "David Gonilski-Pacin"
image: ""
links:
  - label: '`r fontawesome::fa("envelope", fill = "#63D4FD")` Email'
    url: "mailto:davidgonilski@gmail.com"
  - label: '`r fontawesome::fa("twitter", fill = "#63D4FD")` Twitter'
    url: "https://twitter.com/gonilski"
  - label: '`r fontawesome::fa("linkedin", fill = "#63D4FD")` LinkedIn'
    url: "https://www.linkedin.com/in/david-gonilski-813790267/"
  - label: '`r fontawesome::fa("github-square", fill = "#63D4FD")` GitHub'
    url: "https://github.com/davidgonilski"
output:
   postcards::trestles
---

 ```{r load_packages, message = FALSE, warning=FALSE, include=FALSE}
library(fontawesome)

pal1 = "#63D4FD" # pale azure
pal4 = "#AFE9FE" # non-photo blue, 20% lighter
pal6 = "#40B8E0" # 20% darker
pal2 = "#EA7E5D" # burnt sienna
pal3 = "#EC8C6F" # coral
pal5 = "#8C1721" # carmine
pal7 = "#C8504D" # bittersweet shimmer, 20% lighter than carmine

```

---
## Bio

I am Molecular Biologist graduated in Buenos Aires University (UBA), Argentina. 
Currently I work on the [Biomedicine Institute of Buenos Aires](http://ibioba-mpsp-conicet.gov.ar/index.php/en/).

## Research
My name is David Gonilski, and I am a fourth-year PhD student in Biological Sciences at the University of Buenos Aires (UBA), Argentina. During my undergraduate studies, I developed a keen interest in Cancer Biology, aiming to understand the mechanisms behind tumorigenesis and improve cancer treatments. Under the guidance of Eduardo Arzt at the Laboratory of Molecular Targeting, I conducted research on the role of RSUME in tumorigenesis, specifically in angiogenesis and vascularization. I have applied various techniques and published my work in high-impact journals. Now pursuing my Ph.D., I focus on the RSUME oncogene's involvement in the development of Von Hippel Lindau tumors. I have analyzed genomic datasets and performed wet lab experiments to support my findings. Throughout my academic journey, I have co-authored publications and actively engaged in science education. My short-term goals involve enhancing my skills in genomic data analysis and expanding my knowledge of various analysis methods.

## <span style="color:  #63D4FD;"> Education</span>

|  |  |
|:--------------------------------------------------|:----------------|
| **<span style="color:  #63D4FD;"> University of Buenos Aires, Argentina</span>** | [2019 - Present]{style="float:right"} |
| Ph.D. in Kidney Cancer Biology |
|<br>|   |
| **<span style="color:  #63D4FD;"> Cold Spring Harbor Laboratory, New York</span>**| [Summer 2023]{style="float:right"} |
| Statistical Analysis of Genome Scale Data |
|<br>|   |
| **<span style="color:  #63D4FD;"> Biomedicine Institute of Buenos Aires, Argentina</span>**  | [2017 - 2019]{style="float:right"}  |
| M.Sc. in Kidney Cancer Biology and Regenerative Medicine ||
|<br>|   |
| **<span style="color:  #63D4FD;"> University of Southern California, Los Angeles</span>** | [2012 - 2019]{style="float:right"} |
| B.Sc. in Biological Sciences ||

---
  
## <span style="color:  #63D4FD;"> Technical Skills</span>
  
|  |  |
|:------------------------------------------------|:--------------------|
| `r fontawesome::fa("flask", fill = "#AFE9FE")` **Experimental**  | `r fontawesome::fa("bar-chart", fill = "#AFE9FE")` **Bioinformatic** |
| hiPSC Cell Culture | R `r fontawesome::fa("r-project", fill = "gray")` |
| Directed Organoid Differentiation | bash/linux/HPC `r fontawesome::fa("linux", fill = "gray")` |
| Immunofluorescent Staining | sc/snRNA-seq |
| Microsurgery Dissection (<100µm) | sc/snATAC-seq |
| Live Tissue Imaging | ChIP-seq |
| Confocal and Widefield Microscopy | bulkRNA-seq |
| RNA Isolation and cDNA Synthesis | FIJI |
| scRNA-seq library prep | Imaris |
| Genotyping with PCR and Western blot ||

## <span style="color:  #63D4FD;"> In the Press</span>
<br>
June 2023 \| <a href="https://keck.usc.edu/usc-stem-cells-journey-towards-1000-mini-kidneys-begins-with-1-million-from-kidneyx/"><span style="color:  #63D4FD;"> USC Stem Cell’s journey towards 1,000 mini-kidneys begins with $1 million from KidneyX</span></a>

## Teaching

2021-present: Teaching as chief of practical applications, University of Jose C. Paz. Courses taught: Biostatistics and Demography, Microbiology and Parasitology.

2019-2021: Teaching assistant, University of Buenos Aires. Courses taught: Introduction to Molecular Bioinformatics, Biological Chemistry, Genetics I. 

## Works

These are some works i have been involved in:

**[Expression of RSUME is Associated With Poor Prognosis in Clear Cell Renal Carcinoma: Involvement of ROS Related Metabolism](https://www.sciencedirect.com/science/article/pii/S1558767323000678?casa_token=3_WXMMbAo9EAAAAA:CrOUVzqr_Flu8_l4UI54mkudacVHV5ObrPX6JgVrX8FsNmlmWYtXxiUrmKsxuKlQTo293Dnp-A)** | David Gonilski Pacin, Nicolás Ciancio del Giudice, Belén Elguero, Eduardo Arzt. Clinical Genitourinary Cancer (2023)

**[Impact of RSUME Actions on Biomolecular Modifications in Physio-Pathological Processes](https://www.frontiersin.org/articles/10.3389/fendo.2022.864780/full)** | Mariana Fuertes, Belén Elguero, David Gonilski-Pacin, ..., Eduardo Arzt “Impact of RSUME Actions on Biomolecular Modifications in Physio-Pathological Processes”. Review article in Frontiers in Endocrinology (2022).

**[von Hippel-Lindau mutants in renal cell carcinoma are regulated by increased expression of RSUME](https://www.nature.com/articles/s41419-019-1507-3)** | Lucas Tedesco, Belen Elguero, David Gonilski Pacin, ..., Eduardo Arzt. “von Hippel-Lindau mutants in renal cell carcinoma are regulated by increased expression of RSUME”. Cell Death & Disease (2019)

**[Mass Spectrometry-Based Metabolic Fingerprinting Contributes to Unveil the Role of RSUME in Renal Cell Carcinoma Cell Metabolism](https://pubs.acs.org/doi/full/10.1021/acs.jproteome.0c00655)** | Manuela Martinefski, Belen Elguero, María Knott, David Gonilski Pacin, ..., Eduardo Arzt, María Eugenia Monge. Journal of Proteome Research (2021).

## Interests and hobbies
 I love soccer, Messi and the mate. 
 
 ---
  
## <span style="color:  #63D4FD;"> Hobbies</span>
<br>
You can usually find me surfing, playing soccer, or training brazilian jiu-jitsu! I also love cooking and yoga.


